### ISSUE TITLE
Handle dead client's connections ?

### ISSUE THREAD

**Issue by stefan2410** [radu-matei/websocket-manager#11]
Hi,
I suppose,   Web manager could send periodically messages to client, to verify its connection. 
Client could send a REST request only for verification (maybe to include also in its request a timestamp, provided by the manager's initiated message). Then the controller  to send message to web manager to update a "keep alive"  list with clients responses. Web manager periodically could clean the connections without "keep alive" responses.
Unfortunately, I don't have time, for a while,  to help your excellent effort.

**Comment by gmarconi** [comment]
I believe this concept (ping/pong) is already implemented by webSockets, isn't it?

**Comment by stefan2410** [comment]
As I understand (with my poor experience in web sockets)  , the nice thing in Radu's project,  is that the web  sockets manager  can be configured to send only notifications, not to accept incoming messages from external clients. That is very useful in specific environments.  Of course maybe I have not understood well, or simply I don't know.
My thought, based on this blog-post from [Sam Saffron](https://samsaffron.com/archive/2015/12/29/websockets-caution-required)  , is to establish a real-time broadcast only channel to clients,  and all client's interaction to be done through REST calls .
