### ISSUE TITLE
.NET Client - client method parameter - pass individual arguments, not object[]

### ISSUE THREAD

**Issue by radu-matei** [radu-matei/websocket-manager#16]
There should be the possibility of having separate arguments in the lambda for a client method ([unlike right now, where you only pass `object[]` as parameter for the client method](https://github.com/radu-matei/websocket-manager/blob/master/samples/EchoConsoleClient/Program.cs#L11)).

**Comment by Henry00IS** [comment]
D O N E and it's beautiful, like you.
