### ISSUE TITLE
Sample's Documentation

### ISSUE THREAD

**Issue by tanwarsatya** [radu-matei/websocket-manager#26]
Very good work, any explantion how examples working would be good. Not sure how to run the example's.

Satya

**Comment by tanwarsatya** [comment]
Found the blog and used that to run samples provided. 

1. Wasn't able to run the sample provided as it is. 
2. Copied the code in a new Asp.net Core Web Api project and was able to run the MVC sample
3. C# client works but only sometime, still trying to figure out how that can be used by MVC.

Regards
Satya

**Comment by awosztyl** [comment]
Hi Satya,
There are some unhandled exception. They cause that

> C# client works but only sometime


 Try version from #24.

**Comment by tanwarsatya** [comment]
thx for the update
