### ISSUE TITLE
How do I keep a long connection? 

### ISSUE THREAD

**Issue by leeolevis** [radu-matei/websocket-manager#33]
How do I keep a long connection? 
My android app is easy to disconnect

**Comment by radu-matei** [comment]
What client are you using in your Android app?

**Comment by leeolevis** [comment]
Is it normally possible to disconnect? Commands such as ping or pong need to be maintained
Android was developed by other colleagues, and I don't know yet,

**Comment by leeolevis** [comment]
Do you need to return ping or pong？

**Comment by RobSchoenaker** [comment]
Connection management is handled on a lower level. You do not need to do ping/pong. If you answer radu's question, maybe he is able to help.
How is the Android app connecting? If it is using a local connection in an Activity, the connection will drop when your activity is recycled. If you do not want this, you need to use a Service.
