### ISSUE TITLE
Invoking server methods from a client instead of just receiving

### ISSUE THREAD

**Issue by josephgilland** [radu-matei/websocket-manager#43]
Is the invocation of server methods from a client currently supported? If so, is there an example available?

Edit: To clarify, I'm referring to a C# client like a console application.

**Comment by radu-matei** [comment]
At the moment [the .NET Client](https://github.com/radu-matei/websocket-manager/blob/master/src/WebSocketManager.Client/Connection.cs) only supports receiving invocation of client methods.

But creating an invocation and passing it to the server is something rather trivial. [Take a look at how you do it in TypeScript](https://github.com/radu-matei/websocket-manager/blob/master/src/WebSocketManager.Client.TS/src/Connection.ts#L79-L87) and if you want to contribute, add this to the .NET Client.

Will keep this issue open if you or anyone would like to implement this in the .NET Client.

Thanks!

**Comment by Henry00IS** [comment]
This is very old and inaccurate. We now have two-way communication between C#/JS Client <-> Server.
