### ISSUE TITLE
Unnecessary assignment (?)

### ISSUE THREAD

**Issue by sarmis** [radu-matei/websocket-manager#54]
https://github.com/radu-matei/websocket-manager/blob/623d2b29d684e56d8ce9071089916081ae1d7f01/src/WebSocketManager/WebSocketConnectionManager.cs#L50-L52

It's a minor issue but I think that line 52 is unnecessary (List<string> is referenced type and does not need to be reassigned to itself)
- If that is true and I'm not missing something the above three lines can be replaced by:
```
_groups[groupID].Add(socketID);

```

**Comment by radu-matei** [comment]
cc @miker1423, who actually implemented the groups API.

Thanks!

**Comment by miker1423** [comment]
yes, its unnecessary, I'll fix it ASAP.

**Comment by miker1423** [comment]
ready, can someone review the fix? is PR #55

**Comment by radu-matei** [comment]
Closing this as of #55.
Thanks a lot for your contribution!
