### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake.

### ISSUE THREAD

**Issue by Shooshpanius** [radu-matei/websocket-manager#74]
Then client is disconnected (net error or else), server down with error;

System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.

I use NuGet package, hoe to process this errors and drop sockets from disconnected clients withoun server down?

**Comment by awosztyl** [comment]
Look at issue #42 . As @radu-matei wrote: " NuGet is based on a lower version of the repo".

**Comment by Shooshpanius** [comment]
Ok, thx :)
